let levels = {
    level1: new level(
        [
            ["black", "black", "black", "black", "black", "black", "black"],
            ["black", "gray", "gray", "gray", "gray", "white", "black"],
            ["black", "black", "black", "black", "black", "black", "black"],
        ],
        1,
        1
    ),
    level2: new level(
        [
            ["black", "black", "black", "black", "black", "black", "black"],
            ["black", "black", "black", "gray", "black", "black", "black"],
            ["black", "black", "black", "gray", "black", "black", "black"],
            ["black", "gray", "gray", "white", "gray", "gray", "black"],
            ["black", "black", "black", "gray", "black", "black", "black"],
            ["black", "black", "black", "gray", "black", "black", "black"],
            ["black", "black", "black", "black", "black", "black", "black"],
        ],
        1,
        2
    ),
    level3: new level(
        [
            ["black", "black", "black", "black", "black", "black", "black"],
            ["black", "black", "black", "gray", "black", "black", "black"],
            ["black", "black", "black", "gray", "black", "black", "black"],
            ["black", "gray", "gray", "gray", "gray", "white", "black"],
            ["black", "black", "black", "gray", "black", "black", "black"],
            ["black", "black", "black", "gray", "black", "black", "black"],
            ["black", "black", "black", "black", "black", "black", "black"],
        ],
        2,
        3
    ),
    level4: new level(
        [
            ["black", "black", "black", "black", "black", "black", "black"],
            ["black", "black", "gray", "gray", "gray", "black", "black"],
            ["black", "gray", "black", "gray", "black", "gray", "black"],
            ["black", "gray", "gray", "gray", "gray", "gray", "black"],
            ["black", "white", "black", "gray", "black", "gray", "black"],
            ["black", "black", "gray", "gray", "gray", "black", "black"],
            ["black", "black", "black", "black", "black", "black", "black"],
        ],
        6,
        4
    ),
    level5: new level(
        [
            ["black", "black", "black", "black", "black", "black", "black"],
            [
                "black",
                "gray",
                "gray",
                "gray",
                "gray",
                ["white", "black"],
                "black",
            ],
            ["black", "black", "black", "black", "black", "black", "black"],
        ],
        1,
        5
    ),
    level6: new level(
        [
            ["black", "black", "black", "black", "black", "black", "black"],
            ["black", "black", "gray", "black", "gray", "black", "black"],
            [
                "black",
                "gray",
                "gray",
                "black",
                ["white", "black"],
                "gray",
                "black",
            ],
            ["black", "white", "gray", "black", "gray", "black", "black"],
            ["black", "gray", "gray", "gray", "gray", "gray", "black"],
            ["black", "black", "gray", "gray", "gray", "black", "black"],
            ["black", "black", "black", "black", "black", "black", "black"],
        ],
        5,
        6
    ),
    level7: new level(
        [
            ["black", "black", "black", "black", "black", "black", "black"],
            ["black", "black", "black", "gray", "gray", "black", "black"],
            ["black", "gray", "white", "gray", "gray", "gray", "black"],
            ["black", "gray", "black", "gray", "gray", "white", "black"],
            [
                "black",
                ["white", "black"],
                "gray",
                "gray",
                "gray",
                "gray",
                "black",
            ],
            [
                "black",
                "black",
                "gray",
                ["white", "black"],
                "gray",
                "black",
                "black",
            ],
            ["black", "black", "black", "black", "black", "black", "black"],
        ],
        4,
        7
    ),
    level8: new level(
        [
            ["black", "black", "black", "black", "black", "black", "black"],
            ["black", "gray", "gray", "gray", "gray", "gray", "black"],
            ["black", "gray", "black", "gray", "black", "gray", "black"],
            ["black", "gray", "gray", "gray", "black", "gray", "black"],
            [
                "black",
                "gray",
                "gray",
                ["white", "black"],
                "gray",
                "gray",
                "black",
            ],
            ["black", "white", "black", "gray", "gray", "white", "black"],
            ["black", "black", "black", "black", "black", "black", "black"],
        ],
        5,
        8
    ),
    level9: new level(
        [
            [
                "black",
                "black",
                "black",
                "black",
                "black",
                "black",
                "black",
                "black",
                "black",
            ],
            [
                "black",
                "white",
                "brown",
                "brown",
                "black",
                "brown",
                "brown",
                "gray",
                "black",
            ],
            [
                "black",
                "brown",
                "brown",
                "brown",
                "brown",
                "brown",
                "brown",
                "gray",
                "black",
            ],
            [
                "black",
                "brown",
                "black",
                "gray",
                "brown",
                "brown",
                ["white", "black"],
                "gray",
                "black",
            ],
            [
                "black",
                "black",
                "black",
                "brown",
                "brown",
                "brown",
                "brown",
                "gray",
                "black",
            ],
            [
                "black",
                "black",
                "black",
                "black",
                "black",
                "black",
                "black",
                "black",
                "black",
            ],
        ],
        4,
        9
    ),
    level10: new level(
        [
            ["black", "black", "black", "black", "black", "black", "black"],
            ["black", "black", "gray", "white", "gray", "black", "black"],
            ["black", "black", "black", "gray", "black", "gray", "black"],
            [
                "black",
                "gray",
                "gray",
                "gray",
                "gray",
                ["white", "brown"],
                "black",
            ],
            ["black", "black", "black", "gray", "black", "gray", "black"],
            ["black", "black", "gray", "gray", "gray", "black", "black"],
            ["black", "black", "black", "black", "black", "black", "black"],
        ],
        3,
        10
    ),
    level11: new level(
        [
            ["black", "black", "black", "black", "black", "black", "black"],
            [
                "black",
                "brown",
                "brown",
                ["white", "black"],
                "gray",
                "gray",
                "black",
            ],
            ["black", "brown", "brown", "gray", "gray", "gray", "black"],
            ["black", "black", "brown", "gray", "white", "gray", "black"],
            [
                "black",
                "gray",
                "gray",
                "gray",
                "gray",
                ["white", "brown"],
                "black",
            ],
            ["black", "brown", "black", "gray", "black", "gray", "black"],
            ["black", "black", "black", "black", "black", "black", "black"],
        ],
        3,
        11
    ),
};
